### ISSUE TITLE
numbers

### ISSUE THREAD

**Issue by IanaKhitsko** [globerone/MIPZ#3]
https://github.com/globerone/renju/blob/618ecb4c30f80a56890da749c02d7be24c499e19/main.py#L4

please introduce consts for the numbers

**Comment by globerone** [comment]
Created new consts `ROW_LENGTH=19
COL_LENGTH=19
WINNING_LENGTH=5
BLACK_STONE_NUMBER=1
WHITE_STONE_NUMBER=2`
